### ISSUE TITLE
Add the Status tracer feature and Current network usage in the Network monitor application

### ISSUE THREAD

**Issue by ammarraisafti** [caarmen/network-monitor#127]
# Component
**The following is a component of the features I want to propose:**

- Status tracer
- Current network usage

# Proposal description
**Status tracer:** Add the Tracer Status feature in the monitoring settings section, this feature must be designed to be able to monitor local networks, individual computers, remote resources and services that require full attention and overall control.  The check support mode that must be supported is, ICMP PING, TCP Request, HTTP Request, HTTPS Request.

**Current network usage:** Add this feature at the top of the front view of the application, displaying graphs of network usage in real time, namely information about the use of network used for downloading and uploading.

# Mockups / Examples
Below I will show examples of locations or illustrations if the features I recommend are implemented by the Developer.

![Screenshot_2019-04-23-02-15-38-picsay.jpg](https://cdn.steemitimages.com/DQmVWqgV23X3UTefaJ4H3gY7B1FhV7Lt8cxroAXnsR8LSj1/Screenshot_2019-04-23-02-15-38-picsay.jpg)

![Screenshot_2019-04-23-02-15-38-picsay.jpg](https://cdn.steemitimages.com/DQmcUcTwm4qFqNT8epz5dmqiCZTEmgstSeBA8V2EiY2crRn/Screenshot_2019-04-23-02-15-38-picsay.jpg)

![Screenshot_2019-04-23-02-15-38-picsay.jpg](https://cdn.steemitimages.com/DQmNamkh4ykrXfTNHkbAF2as3iMqxdXseTuS8etfVGK6st1/Screenshot_2019-04-23-02-15-38-picsay.jpg)

![Screenshot_2019-04-23-02-15-38-picsay.jpg](https://cdn.steemitimages.com/DQmeGG9xRXtPwvZ5srSk2gb9Q8ZgNPQTfb4y48kUgJoWp3Y/Screenshot_2019-04-23-02-15-38-picsay.jpg)

![Screenshot_2019-04-23-02-15-38-picsay.jpg](https://cdn.steemitimages.com/DQmaZdBwAZ2GyRkeWibd3CuoR3S6qcXeu5kp74zohdLzMMC/Screenshot_2019-04-23-02-15-38-picsay.jpg)

# Benefit
**Status tracer:** With the Tracer Status feature, users can monitor and continue to monitor local networks, each computer, resources and remote services that require full attention and overall control.  This will remind the user of the problem beforehand and produce a detailed report about the state of failure.  Users can also set intervals and dependency checks (Check only when the internet is connected or online if something is online).

**Current network usage:** With the Current network usage feature, users can display a graph of network usage in real time, and get information about the use of the network used to download and upload.

**Comment by caarmen** [comment]
Thanks for the suggestion.

The purpose of Network Monitor is to monitor the status of the device on which the app is installed. There are other tools out there to monitor other devices on the network.  I keep the scope of this app as focused as possible. For example, regarding your other issue #126: this is why I also only have a very basic speed test feature. There are other apps out there that specialize in speed tests, and Network Monitor is not in competition with them.  At some point I even had a link, in the app, to search the Play Store for specialzed speed test apps, in case a user was looking for that. I had to remove it though, because of Google Play Store policies.

I see you've opened lots of issues in lots of different projects on GitHub. May I ask if you're getting some sort of "points" for this, on a system like utopian.io?

**Comment by umair1209** [comment]
@caarmen
Yes, contributors get incentives from utopian after the contributions are reviewed by utopian moderators. 
In order to be eligible for rewards, the PO should acknowledge the suggestions.
