### ISSUE TITLE
Not possible to make screenshot

### ISSUE THREAD

**Issue by fhimpe** [caarmen/network-monitor#96]
When I try to make a screenshot, I get a message that making screenshots is not allowed by the app. Why is this so? I would like to send a screenshot to an app maker to complain about his app not using encrypted connections.

**Comment by caarmen** [comment]
This is strange.  I am able to take screenshots without any problem. I didn't implement anything specific to prevent this. See below.  

What version of Android are you using? What device?  Any custom rom?  Is it possible there is another app running on the phone preventing screenshots?

In my case it's a Huawei P9 Lite running Marshmallow.

Thanks.

Please note, you can also share the data as Excel format.   It might be better than a screenshot, since you could share more data that way.

![screenshot_2017-03-04-14-45-02](https://cloud.githubusercontent.com/assets/1731388/23579231/48ba0ef8-00e9-11e7-884f-da212bc49f19.png)

**Comment by fhimpe** [comment]
Hm, I'm stupid. Seems like I'm confusing different apps. Sorry for the noise :-(

**Comment by caarmen** [comment]
No worries :)
